version: '3.8'

services:
  shario:
    build: .
    ports:
      - '3210:3210'
    #    volumes:
    #      - ./files:/app/files
    #      - ./qrcodes:/app/qrcodes
    #      - ./shared-text.txt:/app/shared-text.txt
    restart: unless-stopped
